### ISSUE TITLE
issue with kali linux 

### ISSUE THREAD

**Issue by Anaselharda** [sophron/wifiphisher#107]
can someone tell what this error means ? Kali updated 

root@AHAC:~/wifiphisher# python wifiphisher.py 
[*] Starting HTTP server at port 8080
Traceback (most recent call last):
  File "wifiphisher.py", line 908, in <module>
    httpd = SecureHTTPServer(("", SSL_PORT), Handler)
  File "wifiphisher.py", line 148, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by sandman6578** [comment]
Give your acces point card a new ip adress
Ifconfig (wlan0) 10.0.0.1

**Comment by zerocolTHS** [comment]
I have same issue and above comment didnt fix it. 
[code][*] Starting HTTP server at port 8080
Traceback (most recent call last):
  File "wifiphisher.py", line 908, in <module>
    httpd = SecureHTTPServer(("", SSL_PORT), Handler)
  File "wifiphisher.py", line 148, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
[/code]

**Comment by sophron** [comment]
Check #47.
