### ISSUE TITLE
Can't Connect to rogue AP on Android?

### ISSUE THREAD

**Issue by nicefellow1234** [sophron/wifiphisher#112]
Greetings..

I hope all will be fine..I am facing an issue..Rogue ap successfully starts but then I can't connect to rogue AP through my Android Phone and can connect to rougue AP through PC but still opens no page  as it should have to redirect me to that Connection Reset page and then WPA password page..!

And now second time I also can't connect to rogue AP through PC also so neither through phone or PC..!

And when I close attack so it throw this error :

Jamming devices: 
[*] 64:6c:b2:0b:c3:99 - c8:3a:35:40:e0:49 - 11 - PTCL-BB
[*] 01:00:0c:cc:cc:cc - c8:3a:35:40:e0:49 - 11 - PTCL-BB
[*] c8:3a:35:40:e0:49 - 11 - PTCL-BB

DHCP Leases: 

HTTP requests: 

^CException in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 639, in channel_hop2
    deauth(monchannel)
  File "wifiphisher.py", line 695, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 251, in send
    __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 243, in __gen_send
    s.close()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 342, in close
    set_promisc(self.ins, i, 0)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 138, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, "")
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 275, in get_if_index
    return int(struct.unpack("I",get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 269, in get_if
    ifreq = ioctl(s, cmd, struct.pack("16s16x",iff))
IOError: [Errno 19] No such device
[!] Closing
root@kali:~/Desktop/wifiphisher#  clear

Regards,
Umair Shah

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.
