### ISSUE TITLE
DHCP, HTTP empty, doesn't work

### ISSUE THREAD

**Issue by Namzaar** [sophron/wifiphisher#115]
Hi, I'm french so please excuse my bad english
I have a problem with wifiphisher. I run it in my own network.
Sometimes, the program have absolutely no effects. Sometimes, deauth my computer, but it can't reconnect.
The "dhcp" and 'http" lines are always empty.
My kali is up to date, i use a AWUS036H for jam (wlan0) and chipset Intel pro Wireless 5100 AGN for AP (wlan1) with this command : python wifiphisher.py -jI wlan0 -aI wlan1

Can you help me?
Thank you :)
![capture du 2015-05-11 18 40 36](https://cloud.githubusercontent.com/assets/12398039/7570213/ceff5ef4-f80e-11e4-921e-a85b0a6ee0bc.png)

**Comment by Sorazal23** [comment]
I have the same issue and I'm not sure if it's my fault or the APs owner. I use a TL-WN722N external card and an Atheros internal which also supports injection..

**Comment by Namzaar** [comment]
Hi.
I have'nt find the solution, when I abort the program (ctrl+C) i have this error message :
[code]
^CException in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 865, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down


[!] Closing
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 641, in channel_hop2
    deauth(monchannel)
  File "wifiphisher.py", line 697, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 251, in send
    __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 234, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 389, in send
    self.outs.sendto(sx, sdto)
error: [Errno 100] Network is down
[/code]

Anybody can help me? Thank you :)

**Comment by sophron** [comment]
Hi, please check the <a href="https://github.com/sophron/wifiphisher/wiki/Frequently-Asked-Questions-(FAQ)">FAQ</a> for an answer on this.
