### ISSUE TITLE
Pressing Ctrl-C quites the program

### ISSUE THREAD

**Issue by RonCan** [sophron/wifiphisher#131]
With the following error:
^CTraceback (most recent call last):
  File "wifiphisher.py", line 974, in <module>
    sniffing(mon_iface, targeting_cb)
  File "wifiphisher.py", line 434, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 575, in sniff
    sel = select([s],[],[],remain)
KeyboardInterrupt

**Comment by blackHatMonkey** [comment]
@RonCan This is true for all the tools running in the terminal. I'm not sure I fully understand the issue you are describing.
