### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by diiegg** [sophron/wifiphisher#134]
hello, i got this error, i hope someone can support
regards

Exception happened during processing of request from ('10.0.0.1', 43810)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 714, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 608, in read
    v = self._sslobj.read(len or 1024)
SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

**Comment by sophron** [comment]
Hi @diiegg,

Can you provide us with more information? Check our <a href="https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines">guidelines</a> to see what we need to know.

**Comment by sophron** [comment]
I just noticed that this has been reported again (#118). I'm closing this, please reply there.
