### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thanh125643** [sophron/wifiphisher#189]
Traceback (most recent call last):
  File "/root/Desktop/wifiphisher-master/wifiphisher.py", line 1014, in <module>
    httpd = SecureHTTPServer((NETWORK_GW_IP, SSL_PORT), Handler)
  File "/root/Desktop/wifiphisher-master/wifiphisher.py", line 154, in __init__
    certfile=PEM
  File "/usr/lib/python2.7/ssl.py", line 509, in __init__
    self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 2] No such file or directory

**Comment by blackHatMonkey** [comment]
@sophron  Duplicate of #158.

@thanh125643 can you provide more information regarding this problem by fallowing [Bug Reporting Guidelines](https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines).

**Comment by sophron** [comment]
@thanh125643, Please provide more details on the relevant thread.
