### ISSUE TITLE
error in lines 984, 510, 710 and 1327. Ubuntu

### ISSUE THREAD

**Issue by miquel09** [sophron/wifiphisher#194]
When I choose an AP it gives me the following error logs:
```
Traceback (most recent call last):
  File "wifiphisher.py", line 984, in <module>
    if not dhcp(dhcpconf, ap_iface):
  File "wifiphisher.py", line 510, in dhcp
    dhcp = Popen(['dnsmasq', '-C', dhcpconf], stdout=PIPE, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I have hostapd installed.

**Comment by sophron** [comment]
You don't have `dnsmaq` though. Try `sudo apt-get install dnsmasq`.

**Comment by miquel09** [comment]
it worked thank you

**Comment by JPaulMora** [comment]
You should close this issue now.
