### ISSUE TITLE
Operation Not Possible Due To RF-KILL

### ISSUE THREAD

**Issue by naflan121** [sophron/wifiphisher#243]
![capture](https://cloud.githubusercontent.com/assets/11876070/14581028/d97e621e-0413-11e6-816e-fcee0c0885ba.PNG)

Why this happen

**Comment by blackHatMonkey** [comment]
This happens because the device is either ```Soft Blocked``` or ```Hard Blocked```. If it is  ```Soft Blocked``` running
```bash
sudo rfkill unblock wlan
```
should fix the error. If the device is ```Hard Blocked``` then you must disconnect and reconnect the device.

**Comment by naflan121** [comment]
yeah it worked but this blocking occur when the victim connect to to evil ap via a PC , I try to connect to my own pc and the captive portal is not appearing automatically or while surfing, For mobile phones working perfectly

**Comment by blackHatMonkey** [comment]
Is the situation you are describing #247?

**Comment by nebula1999** [comment]
Thank you bhM.  This is the error that I now get:

^CException in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 674, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 447, in channel_hop2
    deauth(monchannel)
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 505, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 251, in send
    __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 234, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 389, in send
    self.outs.sendto(sx, sdto)
error: [Errno 100] Network is down

**Comment by blackHatMonkey** [comment]
@nebula1999 
That error is already reported [here](https://github.com/sophron/wifiphisher/issues/242) and is being worked on.
