### ISSUE TITLE
issue when i get wrong password

### ISSUE THREAD

**Issue by michyweb** [sophron/wifiphisher#250]
it happens when someone send password to me

[*] POST 10.0.0.33 wfphshr-wpa-password=jdjdjdd
[*] GET 10.0.0.33
[*] GET 10.0.0.33

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/wifiphisher/wifiphisher/pywifiphisher.py", line 674, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/wifiphisher/wifiphisher/pywifiphisher.py", line 447, in channel_hop2
    deauth(monchannel)
  File "/opt/wifiphisher/wifiphisher/pywifiphisher.py", line 505, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 251, in send
    __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 234, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 389, in send
    self.outs.sendto(sx, sdto)
error: [Errno 100] Network is down

[!] Closing

**Comment by sophron** [comment]
There's #242 open for this.
