### ISSUE TITLE
ValueError: '=' alignment not allowed in string format specifier

### ISSUE THREAD

**Issue by blackHatMonkey** [sophron/wifiphisher#261]
**Version**:
892c177f9f7149e52fcf049a5364127cbeda63e4

**Distribution**: 
Kali 2016

**Description**:
Fails to show any access point after choosing the correct interfaces. It throws a `ValueError` without any user interactions.

**Steps to Reproduce**:
Running 
```
python bin/wifiphisher
```
and letting it go through the normal operations.

**Expected VS actual behavior**: 
Failed to show any target access points

**Script output**:
```
[+] Ctrl-C at any time to copy an access point from below
Traceback (most recent call last):
  File "bin/wifiphisher", line 12, in <module>
    run()
  File "/root/d/wifiphisher/pywifiphisher.py", line 839, in run
    sniffing(mon_iface, targeting_cb)
  File "/root/d/wifiphisher/pywifiphisher.py", line 196, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 595, in sniff
    r = prn(p)
  File "/root/d/wifiphisher/pywifiphisher.py", line 214, in targeting_cb
    target_APs()
  File "/root/d/wifiphisher/pywifiphisher.py", line 226, in target_APs
    .format('num', 'ch', 'ESSID', 'BSSID', 'vendor', width=max_name_size))
ValueError: '=' alignment not allowed in string format specifier
```

**Comment by blackHatMonkey** [comment]
I'm unable to reproduce this error after a system restart. Therefore this error seems to happened due to my system.
