### ISSUE TITLE
Duplicate of #242

### ISSUE THREAD

**Issue by GGGunrunner** [sophron/wifiphisher#276]
Version: commit 0bc2a82b805ab0502cd1e8b313984b5880e46b5b
Kali Openbox: 4.0.0-kali1-amd64 #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) x86_64 GNU/Linux

Any luck with ALFA AWUS036H (Realtek) and ALFA AWUS036NH (Ralink) ?

I run WifiPhisher on two Alfas. wlan0 is autoselected for jamming, wlan2 for rogue.
I can see the jammed macs in the list, GET 10.0.0.x requests. However, neither the laptop, nor the Android or Iphone can stay connected. Apparently, they go half-way but get dropped by DHCP.

As far as I know, 036H is unsuitable for AP mode, but 036NH is ok.
What can be wrong with this setup? Thanks!

Oh, and by the way, thanks for adding a really handy feature of showing AP router vendor name in the list! Really helpful!

**Comment by blackHatMonkey** [comment]
Hi @GGGunrunner 
Thanks for opening an issue.

Are you able to connect to the access point or do you get stuck on `obtaining IP address ` loop.

**Comment by GGGunrunner** [comment]
Partially [SOLVED]. The problem is in DNS resolution.

When my Android phone gets connected to the rogue and I type
www.site.com - it fails to resolve. But typing any IP such as 8.8.8.8
successfully lands on a decoy page.
Below is the snatched password.


[*] GET 10.0.0.19
[*] POST 10.0.0.19 wfphshr-wpa-password=12345678
[*] GET 10.0.0.19


===
After that, I assume, the wifi phisher shuts down the interface
and spews an exception. Thats ok, however could be done more elegantly
in the future. Now I have to find a way to route DNS requests to
a local DNS server and the landing page. Any suggestions?

===

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 693, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 466, in channel_hop2
    deauth(monchannel)
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 524, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 251, in send
    __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 234, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 389, in send
    self.outs.sendto(sx, sdto)
error: [Errno 100] Network is down

We're sorry. An error has been detected after executing _ifconfig_cmd method. If this is the first time you have encountered this error you can try again. Otherwise please report this error so we can fix it.
SIOCSIFFLAGS: Input/output error

**Comment by blackHatMonkey** [comment]
The error you mentioned is already reported in #242 . @sophron might be able to point you to the right direction.
