### ISSUE TITLE
Error while executing the script!

### ISSUE THREAD

**Issue by minoanson** [sophron/wifiphisher#28]
Hi to all, first thanks sophron for sharing this script and second i want to report this issue i have after executing the script

[*] Starting HTTP server at port 8080
[*] Starting HTTPS server at port 443
[+] Networks discovered by wlan0: 5
[+] Starting monitor mode off wlan0
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "wifiphisher.py", line 738, in <module>
    sniffing(mon_iface, targeting_cb)
  File "wifiphisher.py", line 319, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
socket.error: [Errno 100] Network is down

any suggestion?thanks!

**Comment by minoanson** [comment]
wow...i just undestand and i suppose it's my fault...i have only 1 wireless network interface! so sorry sophorn for the trouble and keep going! :+1:
