### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by tb01024632** [sophron/wifiphisher#30]
when i use python wifiphisher.py  then chose a AP ,it shows SIOCADDRT: the network can not get  and   then shows TP-LINK set up on channel 11 via wlan2 on False,and loop the  "Jamming devices:    DHCP Leases:   HTTP requests: ".  

^C
[!] Closing
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 482, in channel_hop2
    deauth(monchannel)
TypeError: 'NoneType' object is not callable

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 663, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down

**Comment by sandman6578** [comment]
which chipsets did you use?? 
need to know for both 2 cards?

**Comment by tb01024632** [comment]
I use the VWmare workstasions' kali linux ,and   I  add a network card

**Comment by sandman6578** [comment]
Wich Chipset your Wireless Cards have???
and did you have two or one??

**Comment by tb01024632** [comment]
yes   I  add  two Wireless Cards   and   one of them for injection


please  show me  the  details of the inject process

**Comment by tb01024632** [comment]
802.11n USB Wireless LAN Card
the  other is  8187

**Comment by sandman6578** [comment]
i need to know the chipset of your first card or give me model number

**Comment by sandman6578** [comment]
dont forget to close the issue guys if it works now

**Comment by sophron** [comment]
I'm closing this. Feel free to re-open if needed.
