### ISSUE TITLE
entry point issue

### ISSUE THREAD

**Issue by r3cursive123** [sophron/wifiphisher#303]
OS: Kali Linux Rolling 4.0.0
Just cloned the repo yesterday

Running into this issue when I run wifiphisher

wlan4=AWUS036NH Alfa Wireless Adapter
wlan2=onboard wireless card 

root@kali:/opt/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.1GIT at 2016-07-06 19:59
[+] Selecting wlan4 interface for the deauthentication attack
[+] Selecting wlan2 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 920, in run
    sniffing(mon_iface, targeting_cb)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 209, in sniffing
    sniff(iface=interface, prn=cb, store=0, stop_filter=stopfilter)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 570, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 484, in __init__
    _flush_fd(self.ins)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 303, in _flush_fd
    os.read(fd,MTU)
OSError: [Errno 100] Network is down

**Comment by blackHatMonkey** [comment]
Hi @r3cursive123 This problem is already reported in #280. Lets continue the discussion there.
