### ISSUE TITLE
wifiphisher Errno 22

### ISSUE THREAD

**Issue by darkshadow016** [sophron/wifiphisher#309]
I have an issue  using wifiphisher-master  version it stuck here no scan just asking for num of the network that didnt scan

```


[*] Starting Wifiphisher 1.1GIT at 2016-07-13 04:22
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables

[+] Choose the [num] of the AP you wish to copy:
```
after ctrl+c it give me this 
```
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 921, in run
    channel, essid, ap_mac = copy_AP()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 273, in copy_AP
    '] of the AP you wish to copy: ')
KeyboardInterrupt
```
second start give me this 

```
[*] Starting Wifiphisher 1.1GIT at 2016-07-13 04:25
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 855, in run
    args.apinterface)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/interfaces.py", line 237, in __init__
    wireless_interfaces = pyric.winterfaces()
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.2.1-py2.7.egg/pyric/pyw.py", line 174, in winterfaces
    return _iostub_(winterfaces)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.2.1-py2.7.egg/pyric/pyw.py", line 1292, in _iostub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.2.1-py2.7.egg/pyric/pyw.py", line 181, in winterfaces
    if iswireless(dev, iosock): wifaces.append(dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.2.1-py2.7.egg/pyric/pyw.py", line 202, in iswireless
    _ = io.io_transfer(iosock, sioch.SIOCGIWNAME, ifh.ifreq(dev))
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.2.1-py2.7.egg/pyric/lib/libio.py", line 73, in io_transfer
    raise pyric.error(e.errno,e.strerror)
pyric.error: [Errno 22] Invalid argumen
```
ifconfig
```

eth0      Link encap:Ethernet  HWaddr 00:1c:23:ad:14:d4  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:21 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1258 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1258 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:98746 (96.4 KiB)  TX bytes:98746 (96.4 KiB)

wlan0     Link encap:Ethernet  HWaddr 00:1d:d9:0b:eb:83  
          inet addr:192.168.1.3  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fd78:6a89:41db:8400:18a2:bec3:8338:1b8e/64 Scope:Global
          inet6 addr: fd78:6a89:41db:8400:21d:d9ff:fe0b:eb83/64 Scope:Global
          inet6 addr: fe80::21d:d9ff:fe0b:eb83/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1400  Metric:1
          RX packets:11790 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14640 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:7283778 (6.9 MiB)  TX bytes:2012766 (1.9 MiB)

wlan1     Link encap:Ethernet  HWaddr e8:94:f6:1f:7b:cc  
          inet addr:192.168.1.15  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fd78:6a89:41db:8400:ea94:f6ff:fe1f:7bcc/64 Scope:Global
          inet6 addr: fe80::ea94:f6ff:fe1f:7bcc/64 Scope:Link
          inet6 addr: fd78:6a89:41db:8400:71b7:df53:9aeb:dc7/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:58688 errors:0 dropped:1411 overruns:0 frame:0
          TX packets:35410 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:49108380 (46.8 MiB)  TX bytes:3564184 (3.3 MiB)
```

any solution
thx

**Comment by wraith-wireless** [comment]
Hey man. There were issues with the PyRIC library version 0.1.2.*. Not sure if one of those was not finding the interfaces or not but I believe upgrading to a minimum of 0.1.3 or preferably 0.1.4 would fix this.

**Comment by darkshadow016** [comment]
Installed 0.1.5 works fine thx bro

**Comment by wraith-wireless** [comment]
Awesome good to hear.

**Comment by sophron** [comment]
Pushed a commit that downloads latest version of PyRIC.

**Comment by Motasembt** [comment]
I have the same problem 
How to upgrade PyRIC library to the working version ?

**Comment by Motasembt** [comment]
I updated pyric  and still no wifi networks and if i press cntrl c and run it again i get the error 22
This app will never work.
