### ISSUE TITLE
ValueError: '=' alignment not allowed in string format specifier

### ISSUE THREAD

**Issue by wikijm** [sophron/wifiphisher#328]
**Version**: commit 277648d7f665215475f4c820b3c9efaa29385e25

**Distribution**: Debian

**Summary**: Error during wifi AP scan

**Description**: Error message when I start `wifiphisher` command

**Steps to Reproduce**: Execute `wifiphisher`

**Expected VS actual behavior**: See all wifi AP around me to select one next.

**Script output**:
`
[*] Starting Wifiphisher 1.1GIT at 2016-09-03 07:14
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
[3;J
[+] Ctrl-C at any time to copy an access point from below
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 811, in run
    sniffing(mon_iface.get_name(), targeting_cb)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 221, in sniffing
    sniff(iface=interface, prn=cb, store=0, stop_filter=stopfilter)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 586, in sniff
    r = prn(p)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 245, in targeting_cb
    target_APs()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 257, in target_APs
    .format('num', 'ch', 'ESSID', 'BSSID', 'vendor', width=max_name_size))
ValueError: '=' alignment not allowed in string format specifier
`

**Comment by sophron** [comment]
Hi @wikijm,

I believe this is now fixed. If you could verify it for me on Debian, that would be great.

**Comment by wikijm** [comment]
It's seems to be fixed. Thanks 👍
