### ISSUE TITLE
PyRIC Error 22 (output from wireless cards included in text). 

### ISSUE THREAD

**Issue by ikon9998** [sophron/wifiphisher#329]
I hope that someone can assist me with my issue. I've done my best to provide (hopefully) useful information to help resolve this problem. Thanks!

I am using the latest version of Wifiphisher (installed via git clone) on a fully updated Kali Linux system (not a VM). I successfully cloned Wifiphisher then ran python setup.py install. However, when I run 'wifiphisher' I get the following error:

```
Starting Wifiphisher 1.1GIT at 2016-09-03 13:15
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 754, in run
    network_manager = interfaces.NetworkManager()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/interfaces.py", line 225, in __init__
    for interface in pyw.winterfaces():
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6-py2.7.egg/pyric/pyw.py", line 142, in winterfaces
    if iosock is None: return _iostub_(winterfaces)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6-py2.7.egg/pyric/pyw.py", line 2202, in _iostub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6-py2.7.egg/pyric/pyw.py", line 146, in winterfaces
    if iswireless(dev, iosock): wifaces.append(dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6-py2.7.egg/pyric/pyw.py", line 167, in iswireless
    else: raise pyric.error(e.errno)
pyric.error: [Errno 22] Invalid parameter

```
Please note that I am using version 0.1.6 of PyRIC which is, I believe, the latest version.

I have checked the user commands requested in other threads. Here they are:

Please note that, at all times, I have wlan0 (internal) and wlan1 (USB) network cards.

ifconfig -a: 

```
wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.103  netmask 255.255.255.0  broadcast 192.168.1.255
        ether aa:bb:cc:dd:ee:ff txqueuelen 1000  (Ethernet)
        RX packets 46361  bytes 61634972 (58.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 34460  bytes 4646205 (4.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:01:02:03:04:05  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```
iwconfig:

```
wlan0     IEEE 802.11abgn  ESSID:"ABC"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: 12:34:56:78:90:12
          Bit Rate=72.2 Mb/s   Tx-Power=15 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=41/70  Signal level=-69 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:110   Missed beacon:0

wlan1     IEEE 802.11bg  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

```
iw dev:

```
phy#2
	Interface wlan1
		ifindex 6
		wdev 0x200000001
		addr 00:01:02:03:04:05 
		type managed
phy#0
	Interface wlan0
		ifindex 3
		wdev 0x1
		addr aa:bb:cc:dd:ee:ff 
		type managed
		channel 1 (2412 MHz), width: 20 MHz, center1: 2412 MHz

```
In Ubuntu 14.04, I managed to get Wifiphisher to start (although I had to manually use airmon-ng) so I can't see how my wireless cards are the issue unless they can be a problem in Kali but not in Ubuntu.

I am more than happy to issue whatever commands you feel will help to resolve this issue. Many thanks for your help!

**Version**: Use `git show | grep commit` command and paste here the output.

`commit 277648d7f665215475f4c820b3c9efaa29385e25`

**Comment by wraith-wireless** [comment]
You caught a bug. I'm going to release a patched version but in the meantime if you edit (as root) the file /usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6-py2.7.egg/pyric/pyw.py
Go to line 156 of pyw.iswireless and add 'return' by changing

    if iosock is None: _iostub_(iswireless, dev)

to 

    if iosock is None: return _iostub_(iswireless, dev)

**Comment by ikon9998** [comment]
Thanks wraith-wireless - your solution worked perfectly.
