### ISSUE TITLE
Module has no run

### ISSUE THREAD

**Issue by FroztIkon** [sophron/wifiphisher#334]
**Version**: 1.1

**Distribution**: Kali Linux 4.3.0 (vmware)

**Description**:

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2390, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'run'

**Comment by sophron** [comment]
Please don't run version 1.1. Download the latest release from <a href="https://github.com/sophron/wifiphisher/archive/master.zip">here</a> instead.
