### ISSUE TITLE
Wifiphisher => Kali Nethunter on Android

### ISSUE THREAD

**Issue by duard** [sophron/wifiphisher#341]
Its possible run this script on Kali Nethunter for Android ?

**Comment by sophron** [comment]
Hi,

I haven't personally tested it. I would be interested to know that too.

**Comment by mcy260** [comment]
i got a lot of errors , any idea how to fix it?

**Comment by crazyboogs** [comment]
'''
root@kali:~# wifiphisher -nJ
[*] Starting Wifiphisher 1.1GIT at 2016-11-08 02:42
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 784, in run    network_manager = interfaces.NetworkManager()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/interfaces.py", line 227, in __init__
    self._interfaces[interface] = NetworkAdapter(interface)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/interfaces.py", line 149, in __init__
    card = pyw.getcard(name)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.2-py2.7.egg/pyric/pyw.py", line 253, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.2-py2.7.egg/pyric/pyw.py", line 2220, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.2-py2.7.egg/pyric/pyw.py", line 254, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.2-py2.7.egg/pyric/pyw.py", line 1041, in devinfo
    'mac': _hex2mac_(nl.nla_find(rmsg, nl80211h.NL80211_ATTR_MAC)),
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.2-py2.7.egg/pyric/pyw.py", line 1805, in _hex2mac_
    return ":".join(['{0:02x}'.format(c) for c in v])
TypeError: 'NoneType' object is not iterable
'''

**Comment by AutinDroid** [comment]
Same problem. Would love to see this work on my Nexus 5

**Comment by Labseb** [comment]
I will try it one OPO with Nethunter soon, stay tuned

**Comment by plauncher** [comment]
Same here

**Comment by serpunja** [comment]
Hello!
My smartphone - Nexus 6
Nethunter - nethunter-shamu-lollipop-3.0.zip
Tried different Interfaces: awus051NH v.2, awus036H, WN722N and WN821N.
I do not know what to do with the error "pyric.error: [Errno 1] Operation not permitted" !

Hopefully wifiphisher v1.2 on Nethunter will work correctly
Please tell me how to update wifipnisher?

That's right? # apt-get upgrade wifiphisher
###  @blackHatMonkey 
@serpunja Wifiphisher is currently not compatible with Nethunter. The project's target os is Kali and therefore we are unable to help you.
### @serpunja
Damn!
A lot of time spent to correctly working wifiphisher.
There was hope.
Here is an example:
1. 
![1](https://cloud.githubusercontent.com/assets/24878620/23405607/1ea5ea08-fdcc-11e6-968b-ac093c1059d2.jpg)
2.
![2](https://cloud.githubusercontent.com/assets/24878620/23405617/284b3824-fdcc-11e6-840e-9827ae2486d2.jpg)
3. 
![3](https://cloud.githubusercontent.com/assets/24878620/23405625/2ef00222-fdcc-11e6-8429-bb6ea3f94810.jpg)

What is the point - wifiphisher, if you can not put in your pocket !?
Sorry.
Thanks, blackHatMonkey
### @kn0wledge
How did you do it ? @serpunja
### @serpunja
@kn0wledge How did you do it ? :
+1:
git clone https://github.com/sophron/wifiphisher.git
cd wifiphisher/
python setup.py install
wifiphisher
Wifiphisher is currently not compatible with Nethunter. ((
Wifiphisher WORKS on NetHunter, but the curve.
fucking error!
### @blackHatMonkey 
If you would like to discuss anything regarding Nethunter please use #341.
### @serpunja
O.K.

**Comment by serpunja** [comment]
Updated Nethunter.
Nethunter ver. 3.15 !
Established Wifiphister: https://github.com/wifiphisher/wifiphisher
git clone https://github.com/wifiphisher/wifiphisher.git # Download the latest revision
cd wifiphisher # Switch to tool's directory
sudo python setup.py install # Install any dependencies (Currently, hostapd, dnsmasq, PyRIC, blessings)
**Again errors.**
![error](https://cloud.githubusercontent.com/assets/24878620/23407290/50394a9e-fdd4-11e6-845d-bc2e215a9731.jpg)
![errors](https://cloud.githubusercontent.com/assets/24878620/23407296/5bfee7a8-fdd4-11e6-8946-81633250ae1b.jpg)
**Command- # wifiphisher --nojamming : 
![nojamming1](https://cloud.githubusercontent.com/assets/24878620/23407399/cdc6f02e-fdd4-11e6-897f-4c3e44961088.jpg)
![nojamming2](https://cloud.githubusercontent.com/assets/24878620/23407427/f0b9d77c-fdd4-11e6-963a-0290f146b680.jpg)

**Comment by serpunja** [comment]
@sophron       **Help!**

**Comment by serpunja** [comment]
Esle to do so:
_pip uninstall wifiphisher
pip uninstall pyric
python setup.py install_
Will be worse?

**Comment by themakerman** [comment]
@blackHatMonkey atleast put the feature that allows to skip the deauth attack and uses internal WiFi adapter of phone to make fake access point and collect the passwords by running server on our phone.

**Comment by themakerman** [comment]
@blackHatMonkey deauth attack can be done using esp8266 wifi chip and we can use the phone for creating fake access point running server for router update.

**Comment by blackHatMonkey** [comment]
@themakerman You can use the `-nJ` to skip deauthentication. I'm not really familiar with android so I need to do more research on this.

**Comment by vay3t** [comment]
I honestly have not read this thread much. In what I could contribute would be this idea. Use as the access point the same wifo of the phone and make deauth with the antenna tplink

**Comment by xdarknet** [comment]
hello everyone. how about now on net hunter? im still get same error

**Comment by serpunja** [comment]
Hi !
After using -nJ.  Wifiphisher raises a fake point only in theory (there is no error).
![nojamming](https://cloud.githubusercontent.com/assets/24878620/24200302/cd7ad522-0f1d-11e7-9f83-de81c4c0e356.jpg)
The client does not have a fake AP.
-----------------------------------
Deauthentication works separately.
![aireplay](https://cloud.githubusercontent.com/assets/24878620/24200354/fbcd579c-0f1d-11e7-8c4c-f916c6efb620.jpg)
mdk3 the same works !

**Comment by laozi999** [comment]
https://www.youtube.com/watch?v=d3VWagtwb_0

This guy explains how to host a fake AP using the Mana Toolkit on Kali Nethunter.

Mana-toolkit uses hostapd, so it must be possible

**Comment by serpunja** [comment]
**Thank you @laozi999 ! 
https://www.youtube.com/watch?v=d3VWagtwb_0 - I already saw  this.**
I need to have a client, after connecting to the fake AP, a page html or php pops up
for some kind of authorization ))
For example:
**"To continue the free wifi, please log in!
At your choice - any social network"** ........)))


How can replace wifiphisher?

**Comment by serpunja** [comment]
MANA good raises fake AP, but does not create phishing-pages!!!
How to edit - start-nat-simple.sh for phishing-pages?

**Comment by laozi999** [comment]
I think mana uses apache so you could find the html (or portal) folder and change the website that is shown when victims connect to your AP

**Comment by themakerman** [comment]
@serpunja How did you got this wrking? I still get the same errors of python......I want to use this in -nJ mode on my nethunter.....any hints how can i get this up and runin?

**Comment by themakerman** [comment]
@blackHatMonkey Do you know how @serpunja managed to run it on nethunter with -nJ.

**Comment by blackHatMonkey** [comment]
@themakerman I have no idea how he did it :cry: . I'm sorry I don't have `nethunter` so maybe someone else can help you in this thread.

**Comment by Parshuram2** [comment]
Any updates on this? Is Wifiphisher going to support Nethunter??

**Comment by sophron** [comment]
@Parshuram2 No updates. I'm planning to work on this when I get a spare device in my hands.

**Comment by bricco1981** [comment]
hi, some progress here. i'm able to create an ap and at the same time to deauth, clients can connect to the ap, but no captive portal. any advice @sophron ? so the only problems now are that captive portals are not working. is that something with android?
