### ISSUE TITLE
NameError: global name 'first_pass' is not defined

### ISSUE THREAD

**Issue by chrisriteco** [sophron/wifiphisher#365]
Kali Linux
commit c0d404537863338c58228c001d79547ff11053c3

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 512, in channel_hop2
    if first_pass == 1:
NameError: global name 'first_pass' is not defined

**Comment by sophron** [comment]
Hi @chrisriteco,

Is this happening every time you run the tool? Make sure sure you are using the latest revision and not one modified version.

**Comment by chrisriteco** [comment]
Updated tonight to the latest version by git. Error still present in the background ('error.log') every run. Command I use 'wifiphisher --nojamming --essid "Wifi" -p oauth-login 2> error.log'.

**Comment by sophron** [comment]
I was able to reproduce this. Will push a fix soon.

**Comment by sophron** [comment]
Just pushed a fix. Please update to the latest revision and let me know if there are any issues.
