### ISSUE TITLE
macos issue

### ISSUE THREAD

**Issue by Keoni80** [sophron/wifiphisher#374]
when i try to use it on macos sierra i have this error:

MacBook-Air:wifiphisher Juan$ wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 16, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/site-packages/scapy/all.py", line 16, in <module>
    from arch import *
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/__init__.py", line 75, in <module>
    from bsd import *
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/bsd.py", line 12, in <module>
    from unix import *
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/unix.py", line 20, in <module>
    from pcapdnet import *
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 30, in <module>
    import pcapy as pcap
ImportError: No module named pcapy
MacBook-Air:wifiphisher Juan$

**Comment by sophron** [comment]
Hi @Keoni80,

This script is only intended to work on GNU/Linux systems. It should not work on Mac OS.

**Comment by AmeddahAchraf** [comment]
Still, you can change the command line from BSD to GNU by using **homebrew** and make it as default.
Please check : https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/
