### ISSUE TITLE
issue when trying to run wifiphisher 

### ISSUE THREAD

**Issue by fr1sk** [sophron/wifiphisher#380]
I installed wifiphisher (first clone, then install) and everything goes ok. But when i try to run it (from bin or from anywhere) i got this error:

> `Traceback (most recent call last):
  File "bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2575, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 16, in <module>
    from scapy.all import *
ImportError: No module named scapy.all

`

Any suggestion how to fix that?

**Comment by iot-werkstatt** [comment]
This is fairly easy. You just have to install scapy on your system. If you are on Debian simply use:

sudo apt-get install python-scapy

Or lookup here:
[http://ask.xmodulo.com/importerror-no-module-named-scapy-all.html](url)
