### ISSUE TITLE
Blessing issue

### ISSUE THREAD

**Issue by Mehran** [sophron/wifiphisher#386]
i just pull update to last version , here is this error 

```
./wifiphisher 
Traceback (most recent call last):
  File "./wifiphisher", line 11, in <module>
    
  File "/root/Desktop/git/wifiphisher/wifiphisher/pywifiphisher.py", line 13, in <module>
    from blessings import Terminal
ImportError: No module named blessings

```

**Comment by Mehran** [comment]
`pip install blessings` . solved my issue .
