### ISSUE TITLE
Variable 'deauthentication' error

### ISSUE THREAD

**Issue by cschweda** [sophron/wifiphisher#447]
Using the current ```master``` branch:

```git clone https://github.com/sophron/wifiphisher.git```

```cd``` into directory, then:

```sudo python setup.py install```

One working interface (not two -- so '--nojamming' option):

```wifiphisher --nojamming --essid "FREE WI-FI" -p oauth-login```

Terminal comes back with:

```[*] Starting HTTP/HTTPS server at ports 8080, 443
[*] Monitor mode: wlan0 - ff:ff:d5:fe:ff:8b
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 879, in run
    if deauthentication.get_clients():
UnboundLocalError: local variable 'deauthentication' referenced before assignment
```

Then back to command line.

**Comment by blackHatMonkey** [comment]
Hi @cschweda thanks for opening a bug report. It should get fixed soon but in the meantime you can try using `1.2` version from [here](https://github.com/sophron/wifiphisher/tree/v1.2).

**Comment by sophron** [comment]
@cschweda It should be good now. Can you please verify?

**Comment by cschweda** [comment]
Nope. Still not fixed. 

Exact same steps as above (after first ```rm -rf wifiphisher```) -- but a different error:

```
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 828, in run
    shutdown(template)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 163, in shutdown
    deauthentication.stop_deauthentication()
AttributeError: 'PhishingTemplate' object has no attribute 'stop_deauthentication'
```

**Comment by blackHatMonkey** [comment]
The problem should be gone now :smile:.

**Comment by cschweda** [comment]
That did it! :)

Thanks for the quick fixes.
