### ISSUE TITLE
Error message !!!

### ISSUE THREAD

**Issue by wermaxta** [sophron/wifiphisher#6]
I get this error
 
[+] Choose the [num] of the AP you wish to copy: 1
Traceback (most recent call last):
  File "wifiphisher.py", line 743, in <module>
    dhcp(dhcpconf, ap_iface)
  File "wifiphisher.py", line 407, in dhcp
    Popen(['ifconfig', mon_iface, 'mtu', '1400'], stdout=DN, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
 

My os is Kali linux 
Python 2.7.3

**Comment by abdallahhamdy** [comment]
yeah happened to me too, i had to manually start monitor mode using airmon and comment this line reset_interfaces() on 710, it did get it past this error message however still trying to figure out how to initiate the dhcp leases

**Comment by strasharo** [comment]
This patch fixed the issue for me - https://github.com/sophron/wifiphisher/pull/8

**Comment by escugs** [comment]
Is not the fix. I just try to change from python to python2 and did work. I made it work all except the dhcp leases. You don't need to remove reset_interface. Just add manual iJ and iA to mon0 or wlna0 depend of your card.

**Comment by wermaxta** [comment]
new error 
python3.3 wifiphisher.py
File "wifiphisher.py", line 231
    print '\n[' + R + '!' + W + '] Closing'
              ^
SyntaxError: invalid syntax

python3.3 --version
Python 3.3.2

**Comment by escugs** [comment]
Yes use version 2.7 . For some strange reason it not working for me too after running at first time as is ok.

**Comment by wermaxta** [comment]
Hi escugs I use python 2.7 and get 
python2.7 wifiphisher.py
[*] Starting HTTP server at port 8080
[*] Starting HTTPS server at port 443
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "wifiphisher.py", line 737, in <module>
    sniffing(mon_iface, targeting_cb)
  File "wifiphisher.py", line 318, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 561, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 455, in __init__
    self.ins.bind((iface, type))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device

**Comment by escugs** [comment]
did you start monitor mode manual?

**Comment by italy2010** [comment]
i tested both method

**Comment by ThaWeatherman** [comment]
@wermaxta Your syntax error in Python 3 is because the `print` function has different syntax in 2 vs 3. The code is not written, it seems, to be compatible with both versions so just stick with 2

**Comment by Hushang123** [comment]
i got this error 
root@kali:~/wifiphisher/bin# wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax

How am i supposed to fix this?? any help will be appreciated 👍
