### ISSUE TITLE
how to fix it?

### ISSUE THREAD

**Issue by Unkez** [sophron/wifiphisher#66]
Traceback (most recent call last):
  File "wifiphisher.py", line 763, in <module>
    start_ap(ap_iface, channel, essid, args)
  File "wifiphisher.py", line 395, in start_ap
    Popen(['hostapd', '/tmp/hostapd.conf'], stdout=DN, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

p.s im a newbie in this :yum:

**Comment by ddworken** [comment]
Do you have hostapd installed?

**Comment by sophron** [comment]
Please check #37.
