### ISSUE TITLE
some help please

### ISSUE THREAD

**Issue by mohsengx** [sophron/wifiphisher#85]
hi,
can anyone help me solve this : 

[ + ] Choose the [num] of the AP you wish to copy: 1
SIOCADDRT: File exists
[*] Starting the fake access point...
Traceback (most recent call last):
  File "wifiphisher.py", line 960, in <module>
    start_ap(ap_iface, channel, essid, args)
  File "wifiphisher.py", line 494, in start_ap
    Popen(['hostapd', '/tmp/hostapd.conf'], stdout=DN, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

thanks

**Comment by sophron** [comment]
Please check #37.
